spring:
  application:
    name: u_pass
  datasource:
    url: ${DATABASE_PASSWORD}
    username: ${DATABASE_URL}
    password: ${DATABASE_USERNAME}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      write-dates-as-timestamps: false
server:
  port: 8080
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
